language: perl
perl:
# - "5.22"
  - "5.18"
# - "5.10"

services:
    - mysql

addons:
  apt:
    packages:
    - expat
    - gettext
    - apache2
    - apache2.2-common
    - apache2-mpm-worker
    - libapache2-mod-perl2
    - libapache2-mod-perl2-dev
    - libssl-dev
    - bind9utils

before_install:
#   - sudo .test/tls-setup.sh
#   - sudo apt-get install -y libextutils-makemaker-perl || echo "nope"
#   - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
      # global/system installed perl modules
#   - sudo cpanm --notest CGI Time::TAI64 Crypt::Mac::HMAC Crypt::KeyDerivation DBD::mysql Test::HTML::Lint Apache::DBI Shell Net::DNS::ZoneFile LWP::UserAgent
#   - sudo cpanm --notest JSON SOAP::Lite XML::Parser Net::DNS MIME::Base32 Net::IP

install:
#   - sudo cp .test/apache-nictool.conf /etc/apache2/sites-enabled/
#   - sudo service apache2 restart || sudo cat /var/log/apache2/error.log
#   - sudo perl .test/create_tables.pl

before_script:

script:

after_success:
after_failure:
#   - pwd
#   - cat /var/log/apache2/error.log
#   - cat /etc/apache2/apache2.conf
#   - ls /usr/lib/apache2/modules/
after_script:

sudo: false
