language: perl
perl:
# - "5.22"
  - "5.18"
# - "5.10"

services:
    - mysql

addons:
  apt:
    packages:
    - expat
    - gettext
    - apache2
    - libapache2-mod-perl2
    - libapache2-mod-perl2-dev
    - libssl-dev
    - bind9utils

before_install:
#   - sudo .test/tls-setup.sh
    - sudo apt-get install -y libextutils-makemaker-perl || echo "nope"
    - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
#   - sudo cpanm --notest Crypt::Mac::HMAC Crypt::KeyDerivation Shell Net::DNS::ZoneFile LWP::UserAgent
      # global/system installed perl modules
    - sudo cpanm --notest JSON MIME::Base32 DBI DBIx::Simple DBD::mysql XML::Parser RPC::XML Digest::SHA1 Apache::DBI CryptX Net::IP SOAP::Lite Digest::HMAC Net::DNS Time::TAI64 BIND::Conf_Parser Test::HTML::Lint

install:
    - cpanm --quiet --installdeps --notest .
    - sudo cp .test/apache-nictool.conf /etc/apache2/sites-enabled/
    - sudo service apache2 restart || sudo cat /var/log/apache2/error.log
    - sudo perl .test/create_tables.pl

before_script:

script:

after_success:
after_failure:
#   - pwd
#   - cat /var/log/apache2/error.log
#   - cat /etc/apache2/apache2.conf
#   - ls /usr/lib/apache2/modules/
after_script:

sudo: required
